seed: 2025
show_progress: False
topk: [5, 10, 20, 50]
metrics: ["NDCG", "MRR"]
field_separator: "\t"
seq_separator: " "
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
# RATING_FIELD: stars
TIME_FIELD: timestamp
# NEG_PREFIX: neg_
ITEM_LIST_LENGTH_FIELD: item_length
LIST_SUFFIX: _list
MAX_ITEM_LIST_LENGTH: 50
shuffle: True
POSITION_FIELD: position_id
load_col:
    inter: [user_id, item_id, timestamp]
    item: ['item_id','title','sales_rank','price','brand','categories','sales_type']

user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"
# val_interval:
#   stars: "(0,inf)"

epochs: 100
train_batch_size: 1024
learner: adam
learning_rate: 0.001
eval_batch_size: 2048
valid_metric: NDCG@5
valid_metric_bigger: True
eval_args:
  split: { "LS": "valid_and_test" }
  group_by: user
  order: TO
  mode: full
neg_sampling: ~
train_neg_sample_args: ~
eval_step: 1
stopping_step: 10
loss_decimal_place: 5
metric_decimal_place: 5
training_neg_sample_num: 0
data_path: 'dataset/'