# device
device: "cuda"
# SASRec
n_layers: 2
n_heads: 2
# hidden_size: 64
inner_size: 64
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: "gelu"
layer_norm_eps: 1e-12
initializer_range: 0.02
initializer_weight: [1.0]
headdim: 16
# loss_type: "CE"

# mamba4rec settings
hidden_size: 64                 # (int) Number of features in the hidden state. 
num_layers: 1                   # (int) Number of Mamba layers.
dropout_prob: 0.2               # (float) Dropout rate.
loss_type: 'CE'                 # (str) Type of loss function. Range in ['BPR', 'CE'].

d_state: 32                     # (int) SSM state expansion factor
d_conv: 4                       # (int) Local convolution width
expand: 2                       # (int) Block expansion factor

# ID Contrast Learning
temperature: 0.2
# Placeholder Contrast Learning
beta: 0.3
phcl_temperature: 1.0
phcl_weight: 1.0
# Representation MoE
expert_num: 4
gate_selection: softmax
start_expert_num: 4
start_gate_selection: softmax
# Temporal MoE
temporal_expert_num: 4
temporal_gate_selection: softmax
interval_scale: 100