# SASRec
n_layers: 2
n_heads: 2
hidden_size: 64
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
hidden_act: "gelu"
layer_norm_eps: 1e-12
initializer_range: 0.02
# initializer_weight: [0.0, 1.0, 1.0]
initializer_weight: [0.0]
loss_type: "CE"
# ID Contrast Learning
temperature: 0.2
# Placeholder Contrast Learning
beta: 0.3
phcl_temperature: 1.0
phcl_weight: 1.0
# Representation MoE
expert_num: 4
gate_selection: softmax
start_expert_num: 4
start_gate_selection: softmax
# Temporal MoE
temporal_expert_num: 4
temporal_gate_selection: softmax
interval_scale: 100